inherit_from:
  - ./rails_pending.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-picket-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rails-accessibility

AllCops:
  Exclude:
    - "**/test/dummy/bin/*"
    - "**/test/dummy/db/*schema.rb"
    - "**/test/dummy/log/**/*"
    - "**/test/dummy/public/**/*"
    - "**/test/dummy/storage/**/*"
    - "**/test/dummy/tmp/**/*"

# rubocop-capybara

Capybara:
  Enabled: true

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/MatchStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/RedundantWithinFind:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

Capybara/VisibilityMatcher:
  Enabled: true

Capybara/RSpec:
  Enabled: true

Capybara/RSpec/HaveSelector:
  Enabled: true

Capybara/RSpec/PredicateMatcher:
  Enabled: true

# rubocop-factory_bot

FactoryBot:
  Enabled: true

FactoryBot/AssociationStyle:
  Enabled: true

FactoryBot/AttributeDefinedStatically:
  Enabled: true

FactoryBot/ConsistentParenthesesStyle:
  Enabled: true

FactoryBot/CreateList:
  Enabled: true

FactoryBot/ExcessiveCreateList:
  Enabled: true

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: true

FactoryBot/FactoryClassName:
  Enabled: true

FactoryBot/FactoryNameStyle:
  Enabled: true

FactoryBot/IdSequence:
  Enabled: true

FactoryBot/RedundantFactoryOption:
  Enabled: true

FactoryBot/SyntaxMethods:
  Enabled: true

# rubocop-rails

Rails:
  Enabled: true

Rails/ActionControllerFlashBeforeRender:
  Enabled: true

Rails/ActionControllerTestCase:
  Enabled: true

Rails/ActionFilter:
  Enabled: false

Rails/ActionOrder:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/ActiveRecordOverride:
  Enabled: true

Rails/ActiveSupportAliases:
  Enabled: true

Rails/ActiveSupportOnLoad:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/ApplicationController:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationMailer:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/ArelStar:
  Enabled: true

Rails/AssertNot:
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/BelongsTo:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

Rails/ContentTag:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: true

Rails/DangerousColumnNames:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/DefaultScope:
  Enabled: false

Rails/Delegate:
  Enabled: true

Rails/DelegateAllowBlank:
  Enabled: true

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true

Rails/DotSeparatedKeys:
  Enabled: true

Rails/DuplicateAssociation:
  Enabled: true

Rails/DuplicateScope:
  Enabled: true

Rails/DurationArithmetic:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Rails/EagerEvaluationLogMessage:
  Enabled: true

Rails/EnumHash:
  Enabled: true

Rails/EnumSyntax:
  Enabled: true

Rails/EnumUniqueness:
  Enabled: true

Rails/EnvLocal:
  Enabled: true

Rails/EnvironmentComparison:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/Exit:
  Enabled: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/FreezeTime:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/I18nLazyLookup:
  Enabled: true

Rails/I18nLocaleAssignment:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: true

Rails/IgnoredColumnsAssignment:
  Enabled: true

Rails/IgnoredSkipActionFilterOption:
  Enabled: true

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/LinkToBlank:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MigrationClassName:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/OrderById:
  Enabled: false

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Pick:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckId:
  Enabled: false

Rails/PluckInWhere:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/RakeEnvironment:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/RedundantActiveRecordAllMethod:
  Enabled: true

Rails/RedundantAllowNil:
  Enabled: true

Rails/RedundantForeignKey:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantReceiverInWithOptions:
  Enabled: true

Rails/RedundantTravelBack:
  Enabled: true

Rails/ReflectionClassName:
  Enabled: true

Rails/RefuteMethods:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

Rails/RequireDependency:
  Enabled: false

Rails/ResponseParsedBody:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/ReversibleMigrationMethodDefinition:
  Enabled: false

Rails/RootJoinChain:
  Enabled: true

Rails/RootPathnameMethods:
  Enabled: true

Rails/RootPublicPath:
  Enabled: true

Rails/SafeNavigation:
  Enabled: true

Rails/SafeNavigationWithBlank:
  Enabled: true

Rails/SaveBang:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

Rails/ScopeArgs:
  Enabled: true

Rails/SelectMap:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/StripHeredoc:
  Enabled: true

Rails/TableNameAssignment:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true

Rails/ToFormattedS:
  Enabled: true

Rails/ToSWithArgument:
  Enabled: true

Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true

Rails/TransactionExitStatement:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: true

Rails/UnknownEnv:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: false

Rails/UnusedRenderContent:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereMissing:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/WhereNotWithMultipleConditions:
  Enabled: true

Rails/WhereRange:
  Enabled: true

# rubocop-rails-accessibility

RailsAccessibility/ImageHasAlt:
  Enabled: true

RailsAccessibility/NoPositiveTabindex:
  Enabled: true

RailsAccessibility/NoRedundantImageAlt:
  Enabled: true
