name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.2, 3.3]
    steps:
      - name: Install packages
        run:
          sudo apt-get update && sudo apt-get install --no-install-recommends -y libjemalloc2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: latest

      - name: Run tests
        run: bin/rake
